"""Signal 1 — Groq LLM classifier (semantic / holistic).

Asks llama-3.3-70b-versatile to assess whether a piece of text reads as
AI-generated and to return a structured JSON verdict. Captures semantic and
stylistic coherence that statistical heuristics miss.

Output contract (planning.md ss.1):
    { "score": float in [0,1] = P(AI-generated), "rationale": str }
"""

import json
import os
import re

from dotenv import load_dotenv
from groq import Groq

from config import GROQ_MODEL, LLM_TEMPERATURE

load_dotenv()

_client = None


def _get_client():
    global _client
    if _client is None:
        api_key = os.environ.get("GROQ_API_KEY")
        if not api_key:
            raise RuntimeError("GROQ_API_KEY is not set (add it to your .env file).")
        _client = Groq(api_key=api_key)
    return _client


_SYSTEM_PROMPT = (
    "You are an AI-text detector for a creative writing platform. You judge "
    "whether a piece of text was written by a human or generated by an AI "
    "language model. Consider holistic, semantic cues: does the writing take a "
    "genuine stance and have an idiosyncratic personal voice (human), or is it "
    "balanced, hedged, uniformly polished, and formulaic (AI)? "
    "Reply ONLY with a single-line JSON object (no markdown, no newlines inside "
    'it) of the form {"ai_probability": <number 0.0-1.0>, "rationale": "<one '
    'short sentence, under 25 words, no line breaks>"}. '
    "ai_probability is your estimated probability the text is AI-generated: "
    "0.0 = clearly human, 1.0 = clearly AI. Be calibrated and cautious — on a "
    "writing platform, wrongly accusing a human is the costlier error, so only "
    "report high probabilities when the signs are strong."
)


def _clamp01(x):
    return max(0.0, min(1.0, float(x)))


def _parse_verdict(raw):
    """Extract {'score','rationale'} from a model reply, tolerating minor
    malformation (stray braces, code fences). Returns None if unparseable.
    """
    if not raw:
        return None
    # Try strict JSON, then the first {...} block, then a bare probability number.
    candidates = [raw]
    block = re.search(r"\{.*?\}", raw, re.DOTALL)
    if block:
        candidates.append(block.group(0))
    for cand in candidates:
        try:
            data = json.loads(cand)
            if isinstance(data, dict) and "ai_probability" in data:
                return {
                    "score": _clamp01(data["ai_probability"]),
                    "rationale": str(data.get("rationale", "")).strip(),
                }
        except (ValueError, TypeError):
            continue
    # Last resort: pull the number out of "ai_probability": 0.9
    m = re.search(r"ai_probability\D*([01](?:\.\d+)?)", raw)
    if m:
        return {"score": _clamp01(m.group(1)), "rationale": raw.strip()[:200]}
    return None


def classify_llm(text):
    """Return {'score': float, 'rationale': str} for the given text.

    Retries once on transient/parse failure, then raises RuntimeError so callers
    can decide how to degrade (the /submit route surfaces this as a 502).
    """
    client = _get_client()
    last_err = None
    for _ in range(2):
        try:
            resp = client.chat.completions.create(
                model=GROQ_MODEL,
                temperature=LLM_TEMPERATURE,
                max_tokens=200,
                messages=[
                    {"role": "system", "content": _SYSTEM_PROMPT},
                    {"role": "user", "content": text},
                ],
            )
            raw = resp.choices[0].message.content
            parsed = _parse_verdict(raw)
            if parsed is not None:
                return parsed
            last_err = f"could not parse verdict from response: {raw!r}"
        except Exception as e:  # network, auth, etc.
            last_err = str(e)
    raise RuntimeError(f"Groq LLM signal failed: {last_err}")


if __name__ == "__main__":
    # Quick manual test: python llm_signal.py
    samples = {
        "clearly AI": (
            "Artificial intelligence represents a transformative paradigm shift in "
            "modern society. It is important to note that while the benefits of AI "
            "are numerous, it is equally essential to consider the ethical "
            "implications. Furthermore, stakeholders across various sectors must "
            "collaborate to ensure responsible deployment."
        ),
        "clearly human": (
            "ok so i finally tried that new ramen place downtown and honestly? "
            "underwhelming. the broth was fine but they put WAY too much sodium in "
            "it and i was thirsty for like three hours after."
        ),
    }
    for label, txt in samples.items():
        result = classify_llm(txt)
        print(f"[{label}] score={result['score']:.2f}  rationale={result['rationale']}")
