"""Signal 1 — Groq LLM classifier (semantic / holistic).

Asks llama-3.3-70b-versatile to assess whether a piece of text reads as
AI-generated and to return a structured JSON verdict. Captures semantic and
stylistic coherence that statistical heuristics miss.

Output contract (planning.md ss.1):
    { "score": float in [0,1] = P(AI-generated), "rationale": str }
"""

import json
import os

from dotenv import load_dotenv
from groq import Groq

from config import GROQ_MODEL, LLM_TEMPERATURE

load_dotenv()

_client = None


def _get_client():
    global _client
    if _client is None:
        api_key = os.environ.get("GROQ_API_KEY")
        if not api_key:
            raise RuntimeError("GROQ_API_KEY is not set (add it to your .env file).")
        _client = Groq(api_key=api_key)
    return _client


_SYSTEM_PROMPT = (
    "You are an AI-text detector for a creative writing platform. You judge "
    "whether a piece of text was written by a human or generated by an AI "
    "language model. Consider holistic, semantic cues: does the writing take a "
    "genuine stance and have an idiosyncratic personal voice (human), or is it "
    "balanced, hedged, uniformly polished, and formulaic (AI)? "
    "Reply ONLY with a JSON object of the form "
    '{"ai_probability": <number 0.0-1.0>, "rationale": "<one sentence>"}. '
    "ai_probability is your estimated probability the text is AI-generated: "
    "0.0 = clearly human, 1.0 = clearly AI. Be calibrated and cautious — on a "
    "writing platform, wrongly accusing a human is the costlier error, so only "
    "report high probabilities when the signs are strong."
)


def _clamp01(x):
    return max(0.0, min(1.0, float(x)))


def classify_llm(text):
    """Return {'score': float, 'rationale': str} for the given text.

    Raises RuntimeError on API/parse failure so callers can decide how to
    degrade (the /submit route surfaces this as a 502).
    """
    client = _get_client()
    try:
        resp = client.chat.completions.create(
            model=GROQ_MODEL,
            temperature=LLM_TEMPERATURE,
            response_format={"type": "json_object"},
            messages=[
                {"role": "system", "content": _SYSTEM_PROMPT},
                {"role": "user", "content": text},
            ],
        )
        raw = resp.choices[0].message.content
        data = json.loads(raw)
    except Exception as e:  # network, auth, malformed JSON, etc.
        raise RuntimeError(f"Groq LLM signal failed: {e}") from e

    if "ai_probability" not in data:
        raise RuntimeError(f"Groq response missing 'ai_probability': {raw!r}")

    return {
        "score": _clamp01(data["ai_probability"]),
        "rationale": str(data.get("rationale", "")).strip(),
    }


if __name__ == "__main__":
    # Quick manual test: python llm_signal.py
    samples = {
        "clearly AI": (
            "Artificial intelligence represents a transformative paradigm shift in "
            "modern society. It is important to note that while the benefits of AI "
            "are numerous, it is equally essential to consider the ethical "
            "implications. Furthermore, stakeholders across various sectors must "
            "collaborate to ensure responsible deployment."
        ),
        "clearly human": (
            "ok so i finally tried that new ramen place downtown and honestly? "
            "underwhelming. the broth was fine but they put WAY too much sodium in "
            "it and i was thirsty for like three hours after."
        ),
    }
    for label, txt in samples.items():
        result = classify_llm(txt)
        print(f"[{label}] score={result['score']:.2f}  rationale={result['rationale']}")
